spring:
  datasource:
    url: jdbc:postgresql://54.180.125.111:5432/goodsple
    driver-class-name: org.postgresql.Driver
    username: goodsple
    password: goodsple

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: goodsple2@gmail.com
    password: qmwwojbswgeesxop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

jwt:
  secret: qvmzxowKQue702T7P3a48ko8gXCbS/G3bJcFnfqWMzc=
  access-validity: 3600000
  refresh-validity: 86400000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package:
    - com.goodsple.features.auth.dto
    - com.goodsple.features.auth.entity
  type-handlers-package: com.goodsple.typehandler

# 디버그 로그
logging:
  level:
    org.springframework.security: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
    com.goodsple.typehandler: DEBUG

# 이미지 업로드
storage:
  type: s3   # local | s3

aws:
  s3:
    bucket: goodsple-0814
    region: ap-northeast-2
    allowed-types: profile,post,product,event,review,banner,auction

# 카카오 연결
kakao:
  client-id:     0f69a9009a695e1a7a933e9cc124cf76
  client-secret: rZH2IkMkykHp0m3mFlF3bnBOHWslBv2N
  redirect-uri:  http://localhost:8080/api/auth/kakao/callback
  rest-api-key: ${KAKAO_REST_API_KEY}   # 교환게시글 등록 시 내위치/주소검색 용도 (삭제금지)

# 이메일 인증 관련 설정
email:
  verification:
    expiration-time: 3   # 인증번호 만료 시간 (3분)
    subject: "이메일 인증 코드"   # 이메일 제목
    from-address: goodsple2@gmail.com  # 실제 발신 이메일 주소
    body-template: "이메일 인증 코드: {code}"  # 이메일 본문 템플릿

# 토스페이먼츠 설정 추가
payment:
  toss:
    # 아래 키는 실제 토스페이먼츠에서 제공하는 테스트용 시크릿 키입니다.
    # 이 키를 사용하면 실제 돈이 나가지 않습니다.
    secret-key: test_sk_pP2YxJ4K87qKNmzvR22zVRGZwXLO
    # 나중에 실제 운영으로 전환할 때 이 키만 실제 키로 바꿔주면 됩니다.