spring:
  datasource:
    url: jdbc:postgresql://54.180.125.111:5432/goodsple
    driver-class-name: org.postgresql.Driver
    username: goodsple
    password: goodsple

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com  # SMTP 서버 (예: Gmail)
    port: 587             # 포트 587 (TLS 연결)
    username: goodsple2@gmail.com
    password: qmwwojbswgeesxop   # ← 16자리 앱 비밀번호, 공백 없이
    properties:
      mail:
        smtp:
          auth: true       # SMTP 인증 필요
          starttls:
            enable: true   # TLS 사용
            required: true

  # 여기서부터 Redis 설정 추가
  data:
    redis:
      host: localhost   # Redis 서버 주소
      port: 6379        # Redis 기본 포트
      timeout: 2000ms   # (선택) 연결 타임아웃

server:
  port: 8080

jwt:
  secret: qvmzxowKQue702T7P3a48ko8gXCbS/G3bJcFnfqWMzc=
  access-validity: 3600000
  refresh-validity: 86400000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package:
    - com.goodsple.features.auth.dto
    - com.goodsple.features.auth.entity
  type-handlers-package: com.goodsple.typehandler

# 디버그 로그
logging:
  level:
#    org.mybatis: DEBUG
    org.springframework.security: DEBUG
    # MyBatis core
    org.apache.ibatis: DEBUG
    # MyBatis-Spring 연동부
    org.mybatis.spring: DEBUG
    # (필요하면) 사용 중인 패키지
    com.goodsple.typehandler: DEBUG

# 카카오 연결
kakao:
  client-id:     0f69a9009a695e1a7a933e9cc124cf76
  client-secret: rZH2IkMkykHp0m3mFlF3bnBOHWslBv2N
  redirect-uri:  http://localhost:8080/api/auth/kakao/callback

# 이메일 인증 관련 설정
email:
  verification:
    expiration-time: 3   # 인증번호 만료 시간 (3분)
    subject: "이메일 인증 코드"   # 이메일 제목
    from-address: goodsple2@gmail.com  # 실제 발신 이메일 주소
    body-template: "이메일 인증 코드: {code}"  # 이메일 본문 템플릿

# 이미지 업로드

# 1) macOS/Linux용 기본 경로

file:
#  upload-dir: ${FILE_UPLOAD_DIR}   # 환경변수 or OS별 프로퍼티로 주입
#  upload-dir: /Users/yein/uploads

---
# 2) Windows에서만 활성화
#spring:
#  config:
#    activate:
#      on-operating-system: Windows
#
#file:
#  upload-dir: C:/Users/uploads