
spring:
  datasource:
    url: jdbc:postgresql://54.180.125.111:5432/goodsple
    driver-class-name: org.postgresql.Driver
    username: goodsple
    password: goodsple

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

jwt:
  secret: qvmzxowKQue702T7P3a48ko8gXCbS/G3bJcFnfqWMzc=
  access-validity: 3600000
  refresh-validity: 86400000


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package:
    - com.goodsple.features.auth.dto
    - com.goodsple.features.auth.entity
  type-handlers-package: com.goodsple.features.auth.enums.handler

logging:
  level:
    org.mybatis: DEBUG

kakao:
  client-id: 0f69a9009a695e1a7a933e9cc124cf76
  redirect-uri: http://localhost:5173/auth/kakao/callback