
spring:
  datasource:
    url: jdbc:postgresql://54.180.125.111:5432/goodsple
    driver-class-name: org.postgresql.Driver
    username: goodsple
    password: goodsple

  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml       # ?? XML ??
    type-aliases-package: com.goodsple                  # DTO ? ??? ??

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080